mydatacarvetool/datacarver/urls.py
from django.conf.urls import url
from . import views

app_name = 'datacarver'
urlpatterns = [
    # /datacarver/
    url(r'^$', views.index, name='index'),

    # /datacarver/<number>
    url(r'^(?P<filesig_id>[0-9]+)/$', views.detail, name='detail'),

    #/datacarver/recover
    url(r'^recover/$', views.recover, name='recover'),

    url(r'^add/$', views.addfile, name='addfsig'),

    url(r'^edit/$', views.editfile, name='editfsig'),

    url(r'^carvermenu/$', views.carverMenu, name='carvermenu'),

    url(r'^carvermain/$', views.carverMain, name='carvermain'),

]

mydatacarvetool/mydatacarvetool/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^datacarver/', include('datacarver.urls')),
]

mydatacarvetool/datacarver/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Filesig(models.Model):
    header = models.CharField(max_length=200)
    trailer = models.CharField(max_length=200, blank=True)
    filetype = models.CharField(max_length=50)
    status = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add = True)
    
    def __str__(self):
        return self.filetype.upper().replace(".","")

class information(models.Model):
    dircopy = models.CharField(max_length=50)
    dirsave = models.CharField(max_length=50)
    sector = models.IntegerField(default=512)
    maxsize = models.IntegerField(default=10000000, 
                                  validators=[
                                      MaxValueValidator(5000000000),
                                      MinValueValidator(1)
                                  ])
    nMax = models.IntegerField(default=1000000,
                                  validators=[
                                      MaxValueValidator(125000000),
                                      MinValueValidator(1)
                                  ])
    threads = models.IntegerField(default=10,validators=[
                                     MinValueValidator(1)
                                  ])
    workers = models.IntegerField(default=10,validators=[
                                     MinValueValidator(1)
                                  ])

mydatacarvetool/datacarver/forms.py
from django import forms
from django.forms import widgets, ModelChoiceField
from .models import information

class infoForm (forms.ModelForm):
    class Meta:
        model = information
        fields = [
            'dircopy',
            'dirsave',
            'sector',
            'maxsize',
            'nMax',
            'threads',
            'workers',
        ]
        widgets = {
            'username': forms.TextInput(attrs={ 'placeholder': 'Enter a username'}),
            'dircopy':  forms.TextInput(attrs={ 'placeholder': 'Enter directory to copy'}),
            'dirsave':  forms.TextInput(attrs={ 'placeholder': 'Enter directory to save'}),
            'sector':  forms.NumberInput(attrs={ 'placeholder': 'Enter number of sectors'}),
            'maxsize': forms.NumberInput(attrs={ 'placeholder': 'Enter max size per file'}),
            'nMax': forms.NumberInput(attrs={ 'placeholder': 'Enter number of iterations'}),
            'threads': forms.NumberInput(attrs={ 'placeholder': 'Enter number of threads'}),
            'workers': forms.NumberInput(attrs={ 'placeholder': 'Enter number of workers'}),
        }

        labels = {
            'dircopy': 'Directory to copy',
            'dirsave': 'Directory to save',
            'sector': 'Number of sectors',
            'maxsize': 'Max size of file',
            'nMax': 'Number of iterations',
            'threads': 'Number of threads',
            'workers': 'Number of workers',
        }

mydatacarvetool/datacarver/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Filesig, information
from .forms import infoForm

# This is the sample tutorial created during FORENSC class AY1718 of DLSU CCS CT
from queue import Queue
import time
from threading import Thread
import os
import sys

os.system('cls') # Clear Screen
q = Queue(10)
import threading


def index(request):
    all_filesigs = Filesig.objects.all()
    delete_id = None
    selectfileid = None
    deletefilesig = None
    filesig_id = None
    selectfile = None
    editid = None
    editfile = None

    if request.method == 'GET':
        filesig_id = request.GET.get('filesigid')
        delete_id = request.GET.get('Yes')
        selectfileid = request.GET.get('selectfileid')
        editid = request.GET.get('editid')
    if filesig_id != None:
        deletefilesig = get_object_or_404(Filesig, pk=filesig_id)

    if delete_id != None:
        deletefilesig = get_object_or_404(Filesig, pk=delete_id)
        deletefilesig.delete()
        return redirect("/datacarver/")
    if selectfileid != None:
        selectfile = get_object_or_404(Filesig, pk=selectfileid)
    if editid != None:
        editfile = get_object_or_404(Filesig, pk=editid)



    context = {
        'all_filesigs': all_filesigs,
        'deletefilesig': deletefilesig,
        'selectfile': selectfile,
        'editfile': editfile,

    }
    return render(request, 'datacarver/index.html', context)


def detail(request, filesig_id):
    filesig = get_object_or_404(Filesig,pk=filesig_id)
 
    return render(request, 'datacarver/filesigdetail.html', {'filesig':filesig})


def recover(request):
    filecarve = []

    form = infoForm(request.POST or None)
    if 'file' in request.POST:
        filecarve =  request.POST.getlist('file')

        for fileid in filecarve:
            filetocarve = get_object_or_404(Filesig, pk=fileid)
            filetocarve.status = 1
            filetocarve.save()
            all_filesigs = Filesig.objects.all()

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        #insert the data carve function
        print("CARVE ME")
        informData = information.objects.all()
        return render(request, 'datacarver/carvermenu.html', {'informData': informData, })

    allfilesigs = Filesig.objects.all()
    context = {'allfilesigs':allfilesigs,
               'form': form,
               }

    return render(request, 'datacarver/recover.html', context)

def addfile(request):
    trail=''

    if 'header' in request.POST:
        head = request.POST['header']
        
    if 'trailer' in request.POST:
        trail = request.POST['trailer']
        
    if 'filetype' in request.POST:
        ftype = request.POST['filetype']
        
    Filesig.objects.create(header=head, trailer=trail, filetype=ftype)

    return redirect("/datacarver/")



def editfile(request):

    trail = ''
    editid = None
    print("HI")
    if 'editid' in request.POST:
        editid = request.POST['editid']
        print(editid)
    if 'header' in request.POST:
        head = request.POST['header']
    if 'trailer' in request.POST:
        trail = request.POST['trailer']
    if 'filetype' in request.POST:
        ftype = request.POST['filetype']
        if editid != None:
            newfilesig = get_object_or_404(Filesig, pk=editid)
            newfilesig.header = head
            newfilesig.trailer = trail
            newfilesig.filetype = ftype
            newfilesig.save()
    return redirect("/datacarver/")

def carverMenu(request):

    return render(request, 'datacarver/carvermenu.html',context)

def worker():
    while True:
        #print("Waiting for image\n")
        item = q.get()
        #print("get Item\n")
        if item is None:
            q.task_done()
            break
        #print("PROCESSING ",item[4],"\n")
        save(item[0],item[1],item[2],item[3],item[4])
        q.task_done()
	
def save(startfile, size, imagectr, pathtosave,filetype):
    image = open(pathtosave+":\\"+filetype.replace(".","")+"\\" + str(imagectr) + filetype,"wb")
    drive.seek(startfile)
    image.write(drive.read(size))
    image.close()
    
def carverMain(request):
    informData = information.objects.last()
    filetocarve = Filesig.objects.filter(status="1")
    for file in filetocarve:
        print(file.filetype)
    print(informData.dircopy,informData.dirsave)
    
    try:
        path = informData.dircopy
        pathtosave = informData.dirsave
        drive = open("\\\\.\\"+path+":", 'rb') # opens the drive D folder in windows. Use /dev/sdb for linux and /dev/disk1 for Mac
        newpath = pathtosave+":\\jpg" #pathtosave+":\\"+ filetype.replace(".", "")
        if not os.path.isdir(newpath):
            os.mkdir(newpath)
        
            
        
    except KeyboardInterrupt:
        print ("Program interrupted. Ctrl+C pressed. Exiting.")
        sys.exit()
    except IOError as e:
        print(e)
        sys.exit()
    print("HELasddasdaO")
    return render(request, 'datacarver/carvermain.html')

mydatacarvetool/datacarver/templates/datacarver/carvermain.html
{% load static %}
<html>
    <head>
        <title>Carver Main</title>
    </head>

    <script type="text/javascript"src="{{ STATIC_URL }} /static/js/jquery-3.2.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>

    <style>
        body {
            overflow-x: hidden;
            margin: 0;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-color: #333;

        }

        .leftnav .contents {
            display: flex;
            flex-direction: row;
            justify-contents: flex-start;
            text-decoration: none;
            background-color: cadetblue;

        }

        .contents div {
            margin: 10px 15px;
        }

        .contents a {
            text-decoration: none;
            color: black;
            font-family: "Raleway";
        }

        .contents a:hover {
            color: white;
        }
        h2 {
            background-color: white;
        }
    </style>

<body>

    <div class="navbar-container">
        <div class="navbar">
            <div class="leftnav">
                <div class="contents">
                    <a href="/datacarver/recover/"><div>
                    Recover
                    </div></a>
                    <a href="/datacarver/"><div>
                    View All
                    </div></a>
                    <a href="#openModal1" onclick=><div>
                    Add Files
                    </div></a>
                </div>
            </div>
            <div class="rightnav">

            </div>

        </div>
    </div>
</body>
</html>

mydatacarvetool/datacarver/templates/datacarver/carvermenu.html
{% load static %}
<html>
    <head>
        <title>Carver Status</title>
    </head>

    <script type="text/javascript"src="{{ STATIC_URL }} /static/js/jquery-3.2.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>

    <style>
        body {
            overflow-x: hidden;
            margin: 0;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-color: #333;

        }

        .leftnav .contents {
            display: flex;
            flex-direction: row;
            justify-contents: flex-start;
            text-decoration: none;
            background-color: cadetblue;

        }

        .contents div {
            margin: 10px 15px;
        }

        .contents a {
            text-decoration: none;
            color: black;
            font-family: "Raleway";
        }

        .contents a:hover {
            color: white;
        }
        h2 {
            background-color: white;
        }
    </style>

<body>

    <div class="navbar-container">
        <div class="navbar">
            <div class="leftnav">
                <div class="contents">
                    <a href="/datacarver/recover/"><div>
                    Recover
                    </div></a>
                    <a href="/datacarver/"><div>
                    View All
                    </div></a>
                    <a href="#openModal1" onclick=><div>
                    Add Files
                    </div></a>
                </div>
            </div>
            <div class="rightnav">

            </div>

        </div>
    </div>
    <div class="container">
        {% if informData %}
            <ul>
                <h2>Information is to be display</h2>
                <a href="{% url 'datacarver:carvermain' %}"><button >Start</button></a>

            </ul>
        {% else %}
            <h2>No Information to display</h2>
        {% endif %}
    </div>
    <script>
         $(document).ready(function () {
            if(window.location.href.indexOf("recover") != -1) {
                  $(".container").css({"visibility": "visible"})

            }
            

        });
    </script>

</body>
</html>

mydatacarvetool/datacarver/templates/datacarver/editfilesig.html
<html>
    <head>
        <title>Edit File Signatures</title>
    </head>
    <script>
        $(document).on("keypress", ".search", function(e) {
            if (e.which == 13) {
            
            }
        });
    </script>
    <style>
        .t {
            margin-right: 1.8em;
        }
        
        .s {
            margin-right: 3.7em;
        }
        
        .s:hover, .t:hover, #u:hover {
            color: dodgerblue;
        }
        
        body {
            margin: 0;
        }
        
        .homepage {
            display: flex;
            flex-direction: column;
            align-content: center;
        }
        
        .container
{    
            margin: 15em;
            margin-top: 1em;
            display: flex;
            flex-direction: row;
            flex-wrap:wrap;
            width:70%;
            height:50%;
}
        
        /*header styling*/
        a:link {
            text-decoration: none;
        }
        
        a:hover {
            cursor: pointer;
        }
        
        .left-container {
            width: 35%;
            display: flex;
            align-items: center;
        }
        
        .right-container {
            width: 30%;
            display: flex;
            flex-direction: row;
            align-items: center;
            margin-top: 1px;
        }
        
        .a-container {
           margin-top: 25px;
            display: flex;
            justify-content: space-between;
            flex-direction: row;
            width: 95%;
            height: 5em;
        }
        
        .b-container {
            display: flex;
            flex-direction: row;
            justify-content: flex-start;
        }
        
        .bar-container {
            display: flex;
            justify-content: center;
            
        }
        
        
    </style>
    
    <body>
        <div class = "homepage">
            <div class = "bar-container">
                <div class = "a-container">
                    <div class = "left-container">
                        Recovery File System
                    </div>
                    <div class = "right-container">
                         <form>
                            <input type="text" class="search" name = "tags" placeholder="Search tag...">
                         </form>
                    </div>

                </div>
            </div>
            
            <div class="bar-container">
                <div>
                    <a href="#" class="b-container"> 
                        <div class = "recover">
                            <span class="s"> Recover </span>
                        </div>
                        <div class = "viewall">
                            <span class="s"> View All </span>
                        </div>
                        <div class = "post">
                            <span class="s"> Add New </span>
                        </div>
                    </a>
                </div>
            </div>
    </body>
</html>

mydatacarvetool/datacarver/templates/datacarver/index.html
{% load static %}
<html>
    <head>
        <title>Data Carver</title>
    </head>

    <script type="text/javascript"src="{{ STATIC_URL }} /static/js/jquery-3.2.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>

    <style>
        body {
            overflow-x: hidden;
            margin: 0;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-color: #333;

        }

        .leftnav .contents {
            display: flex;
            flex-direction: row;
            justify-contents: flex-start;
            text-decoration: none;
            background-color: cadetblue;

        }

        .contents div {
            margin: 10px 15px;
        }

        .contents a {
            text-decoration: none;
            color: black;
            font-family: "Raleway";
        }

        .contents a:hover {
            color: white;
        }

        .container ul {
            display: flex;
            flex-direction: row;
            justify-content: flex-start;
            list-style-type: none;
            flex-wrap: wrap;
        }

        .container ul li {
            margin: 10px;
            background-color: cadetblue;
            padding: 20px;
        }

        .container ul li:hover {
            background-color: black;
        }

        .container ul li a {
            text-decoration: none;
            font-family: "Raleway";
            font-weight: bold;
            color: white;
        }

        #filebuttons button {
            margin-top: 10px;
            padding: 5px 15px;
            font-family: "Raleway";
            border: none;
            cursor: pointer;
        }

        #filebuttons a {
           cursor: pointer;
        }

        #filebuttons #delete:hover {
            background-color: #ff6347;
        }

        #filebuttons #edit:hover {
            background-color: #98ff98;
        }
        .modalDialog {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: rgba(0,0,0,0.8);
        z-index: 99999;
        opacity:0;
        -webkit-transition: opacity 400ms ease-in;
        -moz-transition: opacity 400ms ease-in;
        transition: opacity 400ms ease-in;
        pointer-events: none;
    }

        .modalDialog:target {
            opacity:1;
            pointer-events: auto;
        }

        .modalDialog > div {
            width: 400px;
            position: relative;
            margin: 10% auto;
            padding: 5px 20px 13px 20px;
            border-radius: 10px;
            background: white;
        }

        .x {
            background: #606061;
            color: #FFFFFF;
            line-height: 25px;
            position: absolute;
            right: -12px;
            text-align: center;
            top: 0px;
            width: 19px;
            text-decoration: none;
            font-weight: bold;
            -webkit-border-radius: 12px;
            -moz-border-radius: 12px;
            border-radius: 12px;
            -moz-box-shadow: 1px 1px 3px #000;
            -webkit-box-shadow: 1px 1px 3px #000;
            box-shadow: 1px 1px 3px #000;
        }
        .close2 {
            color: white;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close2:hover,
        .close2:focus {
            color: #000;
            text-decoration: none;
            cursor: pointer;
        }

        #add
        {

            width:100%;
            height:50%;
        }
        .button {
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            margin: 2em 2em;
            width: 89%;
            border: none;
            cursor: pointer;
        }
        input[type="text"]{
            width: 70em;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            padding:  10px;
            margin-top:-0.5em;
            margin-left: 5em;

        }

        .trailer,.filetype,.header
        {
            font-family: Raleway;
            font-weight: bolder;
            text-align: center;
            margin-top: 20px;
            padding: 20px;
            display: flex;
            flex-direction: row;
            width:20%
        }
        .btnacc
        {
            background-color: #4CAF50; /* Green */
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            box-decoration-break: 3;
            border-radius: 3px;
            margin-right: 1em;
        }
        .btndec
        {
            background-color: #EB1818; /* Green */
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            box-decoration-break: 3;
            border-radius: 3px;
            margin-left: 3em;
        }
        .btndec:hover, .btnacc:hover
        {

            cursor: pointer;
        }

        .filechooser {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            height: 100%;
            width: 100%;
            overflow: auto;
            background-color: white;
        }

        .file-container {
            background-color:#f4f4f4;
            margin: 20% auto;
            animation-name: modalopen;
            animation-duration: 1s;
        }

        .close{
          color:#ccc;
          float: right;
          font-size:30px;
          color:#fff;
        }

        .close:hover,.close:focus{
          color:#000;
          text-decoration: none;
          cursor:pointer;
        }

        @keyframes modalopen{
          from{ opacity: 0}
          to {opacity: 1}
        }
         #details {
            position: absolute;
            margin-left: auto;
            margin-right: auto;
            left: 0;
            right: 0;
            visibility: hidden;
            color: white;
            font-family: Raleway;
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
            background-color: #878787;
             width: 30%;
             height: 30%;

        }
         #details:hover
         {
             background-color: lightsteelblue;
         }

        #details .details-container {

            padding: 10px;
        }

        #details .details-container h1{
            font-size: 10em;
        }

        .close3{

          position: absolute;
          top:0;
          right:0.5em;
          font-size:50px;
          color: cadetblue;
        }

        .close3:hover,.close3:focus{
          color:white;
          text-decoration: none;
          cursor:pointer;
        }

    </style>

    <body>

    <div class="navbar-container">
        <div class="navbar">
            <div class="leftnav">
                <div class="contents">
                    <a href="/datacarver/recover/"><div>
                    Recover
                    </div></a>
                    <a href="/datacarver/"><div>
                    View All
                    </div></a>
                    <a href="#openModal1" onclick=><div>
                    Add Files
                    </div></a>
                </div>
            </div>
            <div class="rightnav">

            </div>

        </div>
    </div>

    <div class="container">
        {% if all_filesigs %}
            <ul>
                {% for filesig in all_filesigs %}
                <a href="?selectfileid={{filesig.id}}">
                    <li>
                        {{ filesig.filetype }}
                        <div id="filebuttons">
                            <a href="?filesigid={{filesig.id}}"><button id="delete">Delete</button></a>
                            <a href="?editid={{filesig.id}}"><button id="edit">Edit</button></a>
                        </div>
                    </li>
                </a>
                {% endfor %}
            </ul>
        {% else %}
            <h2>No File Signatures to display</h2>
        {% endif %}
    </div>
    <div id="openModal1" class="modalDialog">
        <div>
            <a href="#x" title="Close" class="x"><span class="close2">&times;</span></a>
             <h2>Create File Signature</h2>
            <div id=add>
                <form action="{% url 'datacarver:addfsig'  %}" method="POST" >
                    {% csrf_token %}
                    <div class="header">Header:
                    <input type="text" name="header" value="" required >
                        </div>
                    <div class="trailer">Trailer:
                    <input type="text" name="trailer" value="" >
                    </div>
                    <div class="filetype">Filetype:
                    <input  type="text" name="filetype" value="" required >
                    </div>
                    <div id = "btn">
                        <button  class="btnacc"  name="save" type="submit" style="margin-bottom:2.5em; margin-left: 4em;" >Save</button>

                       <div class="btndec" name="cancel" onclick="closeModal();">Cancel</div>

                    </div>
                </form>

            </div>

        </div>
    </div>
    <div id="openModal2" class="modalDialog">
        <div>
            <a href="#x" title="Close" class="x"><span class="close2">&times;</span></a>
            <div id=add2>
                <form action="" method="GET" >

                    <div id = "btn2">
                        <h2>Confirmation to delete the file signature</h2>
                        <button  class="btnacc" name="Yes" value="{{deletefilesig.id}}" type="submit" style="margin-bottom:2.5em; margin-left: 4em;" onclick="closeModal()" >Yes</button>

                       <div class="btndec" onclick="closeModal();">No</div>

                    </div>
                </form>

            </div>

        </div>
    </div>
    <div id="openModal3" class="modalDialog">
        <div>
            <a href="#x" title="Close" class="x"><span class="close2">&times;</span></a>
             <h2>Edit File Signature</h2>
            <div id=add>

                <form action="{% url 'datacarver:editfsig' %}" method="POST" >
                    {% csrf_token %}
                    <div class="header">Header:
                    <input type="text" name="header" value="" required >
                        </div>
                    <div class="trailer">Trailer:
                    <input type="text" name="trailer" value="" >
                    </div>
                    <div class="filetype">Filetype:
                    <input  type="text" name="filetype" value="" required >
                    </div>
                    <div id = "btn">
                        <button  class="btnacc"  name="editid" type="submit" style="margin-bottom:2.5em; margin-left: 4em;" value="{{editfile.id}}">Save</button>

                       <div class="btndec" name="cancel" onclick="closeModal();">Cancel</div>

                    </div>
                </form>

            </div>

        </div>
    </div>
     <div id="details">
        <div class="details-container">
            <span class="close3" onclick="closeModal2()">&times;</span>
            <h2>File Type: {{ selectfile.filetype }}</h2>
            <h2>Header: {{ selectfile.header }}</h2>
            <h2>Trailer: {{ selectfile.trailer }}</h2>
        </div>
    </div>

    </body>

    <script>
        $(document).ready(function () {
            if(window.location.href.indexOf("filesigid") != -1) {
                window.location.hash = '#openModal2';


            }
            if(window.location.href.indexOf("selectfileid") != -1) {
                $("#details").css({"visibility": "visible"})


            }
             if(window.location.href.indexOf("editid") != -1) {
                 window.location.hash = '#openModal3';


            }

        });
         function closeModal()
        {
                  window.location.hash = '#x';
        }
         function closeModal2()
        {
                   $("#details").css({"visibility": "hidden"})
        }




    </script>

</html>